name: CI

# Trigger the workflow on push and pull request events to develop and main branches
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        strategy:
          matrix:
            node-version: [16.x, 18.x,20.x]  # Test on different Node.js versions
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
    
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
    
          - name: Install dependencies
            run: npm install
    
         
    
          - name: Build project
            run: npm run build
    
    